add_newline = true # Don't print a new line at the start of the prompt

[line_break]
disabled = true

# Replace the "â¯" symbol in the prompt with "âžœ"
[character]                      # The name of the module we are configuring is "character"
success_symbol = "[ âžœ â˜€ï¸  |](bold green)"     # The "success_symbol" segment is being set to "âžœ" with the color "bold green"
error_symbol =  "[ x ðŸŒ§ï¸  |](bold red)"
#format = """
#[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold green)
#[â”‚](bold green)$directory$rust$package
#[â””â”€>](bold green) """

[package] # Disable the package module, hiding it from the prompt completely
disabled = true

[time]
disabled = false
format = '[ ðŸ•™ \[$time\]]($style)'
time_format = "%A %e, %H:%M"
utc_time_offset = "-5"

[cmd_duration]
min_time = 100
format = '| time: [$duration]($style)'
style = "bold red"
show_notifications = true

#[username]
#disabled = false
#style_user = "white bold"
#style_root = "black bold"
#format = "[$user]($style)"
#show_always = true

#[hostname]
#ssh_only = false
#format =  "@[$hostname](bold red) "
#trim_at = ".companyname.com"
#disabled = false
